import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Play Jeopardy!</title>

                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <h1 className="text-4xl font-bold m-3 text-center">
                    Play Jeopardy!
                </h1>
            </main>
        </div>
    );
};

export default Home;
